"""add surge field to card

Revision ID: c6cb1d2e78b2
Revises: b7998d126463
Create Date: 2024-07-31 12:51:35.817532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6cb1d2e78b2'
down_revision: Union[str, None] = 'b7998d126463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('surge', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'surge')
    # ### end Alembic commands ###
