"""specify quantities in card.py

Revision ID: f24e847ce313
Revises: 6be450df4b2a
Create Date: 2024-07-29 14:56:05.784049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24e847ce313'
down_revision: Union[str, None] = '6be450df4b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('quantity_owned', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('quantity_needed', sa.Integer(), nullable=True))
    op.drop_column('cards', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('quantity', sa.INTEGER(), nullable=True))
    op.drop_column('cards', 'quantity_needed')
    op.drop_column('cards', 'quantity_owned')
    # ### end Alembic commands ###
