"""remove bought from deck

Revision ID: 485089a89017
Revises: 4ba08f4a8a17
Create Date: 2024-07-30 14:40:10.153760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485089a89017'
down_revision: Union[str, None] = '4ba08f4a8a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'bought')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('bought', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
